X_CENTER=540

# Android Status Bar

STATUS_BAR_Y_TOP = 0
STATUS_BAR_Y_CENTER = 31
STATUS_BAR_Y_BOTTOM = 62

# Title Bar

WECHAT_TITLE_BAR_Y_TOP = 63
WECHAT_TITLE_BAR_Y_CENTER = 123
WECHAT_TITLE_BAR_Y_BOTTOM = 182

WECHAT_TITLE_BAR_SEARCH_X_CENTER = 849

# User Region

CONTACT_ITEM_HEIGHT = 129
CONTACT_ITEM_COUNT_FULL = 12
CONTACT_ITEM_NAME_X_START = 130
CONTACT_ITEM_NAME_X_END = 779
CONTACT_ITEM_NAME_Y_START = 20
CONTACT_ITEM_NAME_Y_END = 109

CONTACT_SEP_HEIGHT = 57

CONTACT_SHORTCUT_X_CENTER=1044

CONTACT_SHORTCUT_Y_TOP=183
CONTACT_SHORTCUT_Y_BOTTOM=1784
CONTACT_SHORTCUT_COUNT=29
CONTACT_SHORTCUT_ITEM_HEIGHT=(CONTACT_SHORTCUT_Y_BOTTOM-CONTACT_SHORTCUT_Y_TOP)/CONTACT_SHORTCUT_COUNT

CONTACT_SHORTCUTS={
    'UP':0,
    'FAV':1,
    'A':2,
    'B':3,
    'C':4,
    'D':5,
    'E':6,
    'F':7,
    'G':8,
    'H':9,
    'I':10,
    'J':11,
    'K':12,
    'L':13,
    'M':14,
    'N':15,
    'O':16,
    'P':17,
    'Q':18,
    'R':19,
    'S':20,
    'T':21,
    'U':22,
    'V':23,
    'W':24,
    'X':25,
    'Y':26,
    'Z':27,
    '#':28,
}

CONTACT_SWIPE_UP_DEFAULT_Y_START = 1742
CONTACT_SWIPE_UP_DEFAULT_Y_STOP = 183+18

MATCH_CONTACT_1_Y_CENTER = 381

# WeChat Navigation Bar

WECHAT_NAVIGATION_HOME_X_CENTER = 134
WECHAT_NAVIGATION_CONTACT_X_CENTER = 404

WECHAT_NAVIGATION_BAR_Y_TOP = 1787
WECHAT_NAVIGATION_BAR_Y_CENTER = 1853
WECHAT_NAVIGATION_BAR_Y_BOTTOM = 1919


# Android Navigation Bar

NAVIGATION_BAR_Y_TOP = -1
NAVIGATION_BAR_Y_CENTER = -1
NAVIGATION_BAR_Y_BOTTOM = -1
