X_CENTER = 540

# Android Status Bar

STATUS_BAR_Y_TOP = 0
STATUS_BAR_Y_CENTER = 35
STATUS_BAR_Y_BOTTOM = 71

# Title Bar

WECHAT_TITLE_BAR_Y_TOP = 72
WECHAT_TITLE_BAR_Y_CENTER = 144
WECHAT_TITLE_BAR_Y_BOTTOM = 215

WECHAT_TITLE_BAR_SEARCH_X_CENTER = 802
WECHAT_TITLE_BAR_SEARCH_CANCEL_X_CENTER = 1007
WECHAT_TITLE_BAR_BACK_X_CENTER = 72

# User Region

CONTACT_ITEM_HEIGHT = 156
CONTACT_ITEM_COUNT_FULL = 9
CONTACT_ITEM_NAME_X_START = 152
CONTACT_ITEM_NAME_X_END = 1010
CONTACT_ITEM_NAME_Y_START = 24
CONTACT_ITEM_NAME_Y_END = 131

CONTACT_SEP_HEIGHT = 57

CONTACT_SHORTCUT_X_CENTER = 1050

CONTACT_SHORTCUT_Y_TOP = 216
CONTACT_SHORTCUT_Y_BOTTOM = 17841631
CONTACT_SHORTCUT_COUNT = 29
CONTACT_SHORTCUT_ITEM_HEIGHT = (CONTACT_SHORTCUT_Y_BOTTOM - CONTACT_SHORTCUT_Y_TOP) / CONTACT_SHORTCUT_COUNT

CONTACT_SHORTCUTS = {
    'UP': 0,
    'FAV': 1,
    'A': 2,
    'B': 3,
    'C': 4,
    'D': 5,
    'E': 6,
    'F': 7,
    'G': 8,
    'H': 9,
    'I': 10,
    'J': 11,
    'K': 12,
    'L': 13,
    'M': 14,
    'N': 15,
    'O': 16,
    'P': 17,
    'Q': 18,
    'R': 19,
    'S': 20,
    'T': 21,
    'U': 22,
    'V': 23,
    'W': 24,
    'X': 25,
    'Y': 26,
    'Z': 27,
    '#': 28,
}

CONTACT_SWIPE_UP_1_Y_START = 1530
CONTACT_SWIPE_UP_1_Y_STOP = 216
CONTACT_SWIPE_UP_DEFAULT_Y_START = 1621
CONTACT_SWIPE_UP_DEFAULT_Y_STOP = 216 + 53

MATCH_CONTACT_1_Y_CENTER = 454

INPUT_EDITOR_Y_CENTER = 1721

# WeChat Navigation Bar

WECHAT_NAVIGATION_HOME_X_CENTER = 134
WECHAT_NAVIGATION_CONTACT_X_CENTER = 405

WECHAT_NAVIGATION_BAR_Y_TOP = 1634
WECHAT_NAVIGATION_BAR_Y_CENTER = 1713
WECHAT_NAVIGATION_BAR_Y_BOTTOM = 1793

# Android Navigation Bar

NAVIGATION_BAR_Y_TOP = 1794
NAVIGATION_BAR_Y_CENTER = 1856
NAVIGATION_BAR_Y_BOTTOM = 1919


# ADB IME


ADB_IME_HEIGHT = 68
